name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: BTS Test
      id: bts-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: BTS Test
        setup-command: python -m pip install --upgrade pip
        command: python -m unittest discover -s . -p "test_bst.py"
        timeout: 3
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        BTS-TEST_RESULTS: "${{steps.bts-test.outputs.result}}"
      with:
        runners: bts-test
